base/urls.py
from django.urls import path
from . import views

app_name = 'base'
urlpatterns = [
    path("register",views.register, name="registeration"),
    path("", views.loginpage, name="login"),
    path("forgotpwd", views.forgot, name="forgotpwd"),
    path("getotp", views.getotp, name="getotp"),
    path("resetpwd/<str:pk>", views.resetpwd, name="resetpwd"),
    path("dashboard", views.dashboard, name="dashboard"),
    path("logout", views.logoutpage, name="logout"),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("base.urls")),
]

base/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser

#acc

class User(AbstractUser):
    phone_number = models.CharField(max_length=12, unique=True)
    is_phone_verified = models.BooleanField(default=False)
    otp =models.CharField(max_length=6, null=True, blank=True)
    set_otp_time = models.DateTimeField(null=True, blank=True)
    

    

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User

class CreateregisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','phone_number', 'password1', 'password2']

base/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from django.shortcuts import redirect, render
from django.contrib import messages
from .serializers import registerserializer

from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .decorators import unauthenticated_user
from .models import User
from .forms import CreateregisterForm
from django.views.decorators.csrf import csrf_exempt
import json
from .sms import send_otp_to_phone
from datetime import datetime

def dashboard(request):
    return render(request, 'base/index.html')


expire = 120

# Singin & Singup
# @unauthenticated_user
def register(request):
    form = CreateregisterForm()
    if request.method=='POST':
            form = CreateregisterForm(request.POST)
            if form.is_valid():
                user=form.save()
                username = form.cleaned_data.get('name')
                User.objects.create(user=user,name=user.name, phone = user.phone)
                messages.success(request,'Account was created for '+ username)
                return redirect('base:login')
    context={'form':form}
    return render(request,'base/register.html', context)
             
# @unauthenticated_user
def loginpage(request):
    if request.method=='POST':
            phone=request.POST.get('phone')
            password=request.POST.get('password')
            # user=authenticate(request,phone_number=phone,password=password)
            user = User.objects.get(phone_number = phone)
            if user.check_password(password):
                login(request,user)
                return redirect('base:dashboard')
            else:
                messages.info(request,'Email or Password is incorrect! ')
    context={}
    return render(request,'base/login.html')




def forgot(request):
    if request.method == 'POST':
        phone=request.POST.get('phone')
        otp=request.POST.get('otp')
        user = User.objects.get(phone_number=phone)
        if user:
            if otp == user.otp:
                t1 = user.set_otp_time
                t2 = datetime.now().astimezone()
                t = t2 - t1
                if t.total_seconds() < expire:
                    return redirect('base:resetpwd', pk=user.id)
                    # context = {'phone':phone}
                    # return render(request, 'base/resetpwd.html', context)
                else:
                    messages.info(request, "Your verification code is expire, please request otp again.")
            else: messages.info(request, "Incorrect verification code.")
        else: messages.info(request, "Incorrect phone number.")
    
    return render(request, 'base/forgotpwd.html')

@csrf_exempt
def getotp(request):
    try:
        body = request.body.decode('utf-8')
        data = json.loads(body)
        user = User.objects.get(phone_number=data['phone'])
        otp = send_otp_to_phone(data['phone'])
        user.otp = otp
        user.set_otp_time = datetime.now()
        user.save()
        if(otp):
            return JsonResponse({'otp':otp})
    except Exception as e:
        return JsonResponse({'otp':'None'})

def resetpwd(request, pk):
    if request.method == 'POST':
        pass1 = request.POST.get('pass1')
        pass2 = request.POST.get('pass2')
        if pass1 == pass2:
            user = User.objects.get(id=int(pk))
            return redirect('base:dashboard')
        messages.info(request,'The two password does not match each other.')
    return render(request, 'base/resetpwd.html')
                     
def logoutpage(request):
    logout(request)
    return redirect('base:login')

templates/base/forgotpwd.html
{% block content %}

<style>
    @import url("https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap");
    :root {
      --color-dark:#000000;
      --color-gray-dark:#343a40;
      --color-white:#ffffff;
      --color-blue:#009ADA;
      --color-teal:#20c997;
      --color-cyan:#17a2b8;
      --color-warning:#dc3545;
      --color-light:#f8f9fa;
      }
  
   * {
      font-family: "DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans",
          "Helvetica Neue", sans-serif;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      text-rendering: optimizeLegibility;
      /* color: inherit; */
      font-size: inherit;
     }
  
     body{
         background-color: var(--color-light);
     }
  
     i{
         color: var(--color-gray-dark);
     }
     
     a{
         text-decoration: none;
     }
      .signin{
          width: 30%;
          margin: auto;
          margin-top: 8rem;
          display: grid;
          grid-template-rows: 1fr;
          background-color: var(--color-white);   
          text-align: center;
      }
  
      .signin .header{
          background-color: var(--color-gray-dark);
      }
  
      .header h1{
          font-size: 3rem;
          color: var(--color-light);
      }
  
      form{
          width: 85%;
          margin: auto;
          margin-top: 1rem;
      }
  
      form div{
          display: grid;
          grid-template-columns: 1fr 1fr;
          padding: 0.6rem 1rem;
          text-align: left;
      }
  
      .btn{
          border: none;
          background-color: var(--color-gray-dark);
          color: var(--color-white);
          font-size: 1.5rem;
          width: 10rem;
          padding: 0.3rem;
  
      }
     
      p{
         width: 60%;
         margin: auto;
         margin-top: 1rem;
         margin-bottom: 1.5rem;
       }
       
    .otp{
        cursor: pointer;
        color:#009ADA;
    }
     
  </style>

<div class="signin">
    <div class="header">
        <h1>S&S</h1>
    </div>

    <form action="" method="POST">
        {% csrf_token %}
        <div>
            <label for="">Phone</label>
            <input type="text" name="phone" id="phone-no" placeholder="09........." required>
        </div>
        
        <div>
            <label for="" onclick="getopt()" class="otp">Get Otp Code:</label>
            <input type="text" name="otp">
        </div>
        
        <input type="submit" class="btn" value="Next Step">
    
    </form>

    {% for message in messages %}
      <p>{{message}}</p>
    {% endfor %}
    
</div>

<script>
    async function getopt(){
        var phone = document.querySelector("#phone-no").value;
        fetch('http://localhost:8000/getotp', {
            method: 'POST',
            body: JSON.stringify({
                phone:phone,

            }),
            headers: {
                'Content-type': 'application/json; charset=UTF-8',
            }
            })
            .then(function(response){ 
            return response.json()}).then(function(data){ 
                if(data['otp'] == 'None'){
                    window.alert("Your phone number does not exist in our system.")
                }else{
                    console.log(data)
                }
            })           
    }
    

</script>


{% endblock %}

templates/base/index.html
{% extends 'main.html' %}
{% block content %}

<h1><a href="{% url 'base:logout' %}">Logout</a></h1>

{% endblock%}

templates/base/login.html
{% block content %}

<style>
    @import url("https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap");
    :root {
      --color-dark:#000000;
      --color-gray-dark:#343a40;
      --color-white:#ffffff;
      --color-blue:#009ADA;
      --color-teal:#20c997;
      --color-cyan:#17a2b8;
      --color-warning:#dc3545;
      --color-light:#f8f9fa;
      }
  
   * {
      font-family: "DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans",
          "Helvetica Neue", sans-serif;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      text-rendering: optimizeLegibility;
      /* color: inherit; */
      font-size: inherit;
     }
  
     body{
         background-color: var(--color-light);
     }
  
     i{
         color: var(--color-gray-dark);
     }
     
     a{
         text-decoration: none;
     }
      .signin{
          width: 30%;
          margin: auto;
          margin-top: 8rem;
          display: grid;
          grid-template-rows: 1fr;
          background-color: var(--color-white);   
          text-align: center;
      }
  
      .signin .header{
          background-color: var(--color-gray-dark);
      }
  
      .header h1{
          font-size: 3rem;
          color: var(--color-light);
      }
  
      form{
          width: 85%;
          margin: auto;
          margin-top: 1rem;
      }
  
      form div{
          display: grid;
          grid-template-columns: 1fr 1fr;
          padding: 0.6rem 1rem;
          text-align: left;
      }
  
      .btn{
          border: none;
          background-color: var(--color-gray-dark);
          color: var(--color-white);
          font-size: 1.5rem;
          width: 7rem;
          padding: 0.3rem;
  
      }
     
      p{
         width: 60%;
         margin: auto;
         margin-top: 1rem;
         margin-bottom: 1.5rem;
       }
  
     
  </style>

<div class="signin">
    <div class="header">
        <h1>S&S</h1>
    </div>

    <form action="" method="POST">
        {% csrf_token %}
        <div>
            <label for="">Phone:</label>
            <input type="text" name="phone">
        </div>
        
        <div>
            <label for="">Password:</label>
            <input type="password" name="password">
        </div>
        
        <input type="submit" class="btn" value="Login">
    
    </form>

    {% for message in messages %}
      <p>{{message}}</p>
    {% endfor %}

    <p>Don't have an account? <a href="{% url 'base:registeration' %}">Sign Up</a></p>
    
</div>



{% endblock %}

templates/base/register.html
{% block content %}

<style>
  @import url("https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap");
  :root {
    --color-dark:#000000;
    --color-gray-dark:#343a40;
    --color-white:#ffffff;
    --color-blue:#009ADA;
    --color-teal:#20c997;
    --color-cyan:#17a2b8;
    --color-warning:#dc3545;
    --color-light:#f8f9fa;
    }

 * {
    font-family: "DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans",
        "Helvetica Neue", sans-serif;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    text-rendering: optimizeLegibility;
    /* color: inherit; */
    font-size: inherit;
   }

   body{
       background-color: var(--color-light);
   }

   i{
       color: var(--color-gray-dark);
   }
   
   a{
       text-decoration: none;
   }
    .sign-up{
        width: 30%;
        margin: auto;
        margin-top: 8rem;
        display: grid;
        grid-template-rows: 1fr;
        background-color: var(--color-white);   
        text-align: center;
    }

    .sign-up .header{
        background-color: var(--color-gray-dark);
    }

    .header h1{
        font-size: 3rem;
        color: var(--color-light);
    }

    form{
        width: 85%;
        margin: auto;
        margin-top: 1rem;
    }

    form div{
        display: grid;
        grid-template-columns: 1fr 1fr;
        padding: 0.6rem 1rem;
        text-align: left;
    }

    .btn{
        border: none;
        background-color: var(--color-gray-dark);
        color: var(--color-white);
        font-size: 1.5rem;
        width: 7rem;
        padding: 0.3rem;

    }
   
    p{
       width: 60%;
       margin: auto;
       margin-top: 1rem;
       margin-bottom: 1.5rem;
   }

   
</style>

<div>
    <div class="sign-up">
        <div class="header">
           <h1>Construction</h1>
        </div>
        
    
        <form method="POST" action="">
            {% csrf_token %}
            <div>
                <label for="">Phone:</label>
                {{form.phone_number}}
            </div>
            <div>
                <label for="">Password:</label>
                {{form.password1}}
            </div>
            
            <div>
                <label for="">Confrim Password:</label>
                {{form.password2}}
            </div>
            <input type="submit" class="btn" value="Next">
        
        </form>

        <form method="POST" action="">
            {% csrf_token %}
            <div>
                <label for="">Verification:</label>
                <input type="text" name="otp-code">
            </div>
            <input type="submit" class="btn" value="OK">
        
        </form>
    
    {{form.errors}}
    
    
        <p>Already have account? <a href="{% url 'base:login' %}">Login</a></p>
    </div>
</div>




{% endblock %}

templates/base/resetpwd.html
{% block content %}

<style>
    @import url("https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&display=swap");
    :root {
      --color-dark:#000000;
      --color-gray-dark:#343a40;
      --color-white:#ffffff;
      --color-blue:#009ADA;
      --color-teal:#20c997;
      --color-cyan:#17a2b8;
      --color-warning:#dc3545;
      --color-light:#f8f9fa;
      }
  
   * {
      font-family: "DM Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Open Sans",
          "Helvetica Neue", sans-serif;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      text-rendering: optimizeLegibility;
      /* color: inherit; */
      font-size: inherit;
     }
  
     body{
         background-color: var(--color-light);
     }
  
     i{
         color: var(--color-gray-dark);
     }
     
     a{
         text-decoration: none;
     }
      .signin{
          width: 30%;
          margin: auto;
          margin-top: 8rem;
          display: grid;
          grid-template-rows: 1fr;
          background-color: var(--color-white);   
          text-align: center;
      }
  
      .signin .header{
          background-color: var(--color-gray-dark);
      }
  
      .header h1{
          font-size: 3rem;
          color: var(--color-light);
      }
  
      form{
          width: 85%;
          margin: auto;
          margin-top: 1rem;
      }
  
      form div{
          display: grid;
          grid-template-columns: 1fr 1fr;
          padding: 0.6rem 1rem;
          text-align: left;
      }
  
      .btn{
          border: none;
          background-color: var(--color-gray-dark);
          color: var(--color-white);
          font-size: 1.5rem;
          width: 7rem;
          padding: 0.3rem;
  
      }
     
      p{
         width: 60%;
         margin: auto;
         margin-top: 1rem;
         margin-bottom: 1.5rem;
       }
  
     
  </style>

<div class="signin">
    <div class="header">
        <h1>S&S</h1>
    </div>

    <form action="" method="POST">
        {% csrf_token %}
        <div>
            <label for="">New Password:</label>
            <input type="text" name="pass1" required>
        </div>
        
        <div>
            <label for="">Confrim Password:</label>
            <input type="password" name="pass2" required>
        </div>
        
        <input type="submit" class="btn" value="OK">
    
    </form>

    {% for message in messages %}
      <p>{{message}}</p>
    {% endfor %}
    
</div>



{% endblock %}

templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contruction</title>
</head>
<body>
    {% block content %}
    
    {% endblock %}
</body>
</html>